name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi "ruff>=0.12" uvicorn sqlalchemy alembic pytest
          # если есть requirements.txt / requirements-dev.txt — добавь строку:
          # pip install -r requirements.txt
          # pip install -r requirements-dev.txt

      - name: Run Ruff (lint)
        run: |
          ruff check app tests

      - name: Run Pytest
        run: |
          pytest tests/
